<!DOCTYPE html>
<html lang="<?= esc($lang ?? 'en') ?>">
<head>
<meta charset="UTF-8">
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 10pt; color: #1a1a1a; padding: 20mm; }
  h1 { font-size: 18pt; color: #6d28d9; margin-bottom: 4mm; }
  h2 { font-size: 11pt; color: #4c1d95; border-bottom: 1px solid #ddd6fe; margin: 5mm 0 2mm; padding-bottom: 1mm; }
  .header { display: flex; justify-content: space-between; margin-bottom: 8mm; }
  .logo { font-size: 20pt; font-weight: bold; color: #6d28d9; }
  .addresses { display: grid; grid-template-columns: 1fr 1fr; gap: 10mm; margin-bottom: 6mm; }
  .addr-box { font-size: 9pt; line-height: 1.6; }
  .addr-box strong { display: block; font-size: 10pt; color: #4c1d95; margin-bottom: 1mm; }
  table { width: 100%; border-collapse: collapse; }
  th { background: #6d28d9; color: #fff; padding: 2mm 3mm; text-align: right; font-size: 10pt; }
  th.left { text-align: left; }
  td { padding: 2mm 3mm; border-bottom: 1px solid #ede9fe; text-align: right; font-size: 10pt; }
  td.left { text-align: left; }
  tr:nth-child(even) td { background: #faf5ff; }
  .subtotal-row td { background: #f3f0ff; }
  .tax-row td { color: #555; }
  .total-row td { font-size: 12pt; font-weight: bold; background: #ede9fe; color: #4c1d95; }
  .source-badge { display: inline-block; background: #ede9fe; color: #6d28d9; padding: 0.5mm 2mm; border-radius: 2mm; font-size: 8pt; font-weight: bold; }
  .footer { margin-top: 10mm; border-top: 1px solid #ddd; padding-top: 3mm; font-size: 8pt; color: #888; }
  .legal-note { background: #f0f9ff; border: 1px solid #bae6fd; border-radius: 2mm; padding: 3mm; margin-top: 3mm; font-size: 8.5pt; color: #0c4a6e; line-height: 1.5; }
  .meta-table td { border: none; padding: 1mm 3mm; }
  .meta-table td:first-child { color: #777; font-size: 9pt; }
  .meta-table td:last-child { font-weight: bold; }
</style>
</head>
<body>

<div class="header">
  <div>
    <div class="logo"><?= esc($tenant['company_name'] ?? 'WorkHub') ?></div>
    <div style="font-size:8pt;color:#777;margin-top:1mm;"><?= esc($tenant['address'] ?? '') ?></div>
  </div>
  <div style="text-align:right;">
    <div style="font-size:18pt;font-weight:bold;color:#6d28d9;">INVOICE</div>
    <span class="source-badge">WorkHub</span>
  </div>
</div>

<div class="addresses">
  <div class="addr-box">
    <strong>From</strong>
    <?= esc($tenant['company_name'] ?? '') ?><br>
    <?= nl2br(esc($tenant['address'] ?? '')) ?><br>
    VAT: <?= esc($tenant['vat_number'] ?? '—') ?>
  </div>
  <div class="addr-box">
    <strong>Bill To</strong>
    <?= esc($customer['name'] ?? '—') ?><br>
    <?= nl2br(esc($customer['address'] ?? '')) ?>
  </div>
</div>

<table class="meta-table" style="margin-bottom:4mm;">
  <tr><td>Invoice Number</td><td><?= esc($invoice['invoice_number'] ?? '—') ?></td></tr>
  <tr><td>Invoice Date</td><td><?= esc(date('d.m.Y', strtotime($invoice['created_at'] ?? 'now'))) ?></td></tr>
  <tr><td>Due Date</td><td><?= esc($invoice['due_date'] ? date('d.m.Y', strtotime($invoice['due_date'])) : '—') ?></td></tr>
  <tr><td>Completion Ref</td><td><?= esc('CC-' . str_pad($invoice['source_ref_id'] ?? 0, 6, '0', STR_PAD_LEFT)) ?></td></tr>
  <tr><td>Task Ref</td><td><?= esc('WO-' . str_pad($task['id'] ?? 0, 6, '0', STR_PAD_LEFT)) ?></td></tr>
</table>

<h2>Line Items</h2>
<table>
  <tr>
    <th class="left">Description</th>
    <th>Qty</th>
    <th>Unit</th>
    <th>Unit Price</th>
    <th>Amount</th>
  </tr>
  <?php $subtotal = 0; foreach (($lines ?? []) as $line): $amt = floatval($line['line_extension_amount'] ?? 0); $subtotal += $amt; ?>
  <tr>
    <td class="left"><?= esc($line['description']) ?></td>
    <td><?= esc(number_format(floatval($line['quantity']), 2)) ?></td>
    <td><?= esc($line['unit_code'] ?? '—') ?></td>
    <td><?= number_format(floatval($line['unit_price'] ?? 0), 2) ?> €</td>
    <td><?= number_format($amt, 2) ?> €</td>
  </tr>
  <?php endforeach; ?>
  <tr class="subtotal-row"><td class="left" colspan="4"><strong>Subtotal (net)</strong></td><td><?= number_format($subtotal, 2) ?> €</td></tr>
  <?php $taxRate = floatval($invoice['tax_percent'] ?? 19); $taxAmt = $subtotal * $taxRate / 100; ?>
  <tr class="tax-row"><td class="left" colspan="4">VAT (<?= $taxRate ?>%)</td><td><?= number_format($taxAmt, 2) ?> €</td></tr>
  <tr class="total-row"><td class="left" colspan="4">Total Due</td><td><?= number_format($subtotal + $taxAmt, 2) ?> €</td></tr>
</table>

<div class="legal-note">
  This invoice was automatically generated by WorkHub upon completion of field service task
  WO-<?= esc(str_pad($task['id'] ?? 0, 6, '0', STR_PAD_LEFT)) ?>.
  Dual signature obtained per eIDAS 910/2014. Records retained 10 years per §257 HGB / §147 AO.
  Payment within <?= esc($invoice['payment_terms_days'] ?? 14) ?> days.
</div>

<div class="footer">
  <?= esc($tenant['company_name'] ?? 'WorkHub') ?> ·
  Bank: <?= esc($tenant['bank_account'] ?? '—') ?> ·
  IBAN: <?= esc($tenant['iban'] ?? '—') ?> ·
  BIC: <?= esc($tenant['bic'] ?? '—') ?>
</div>
</body>
</html>
