<!DOCTYPE html>
<html lang="<?= esc($lang ?? 'en') ?>">
<head>
<meta charset="UTF-8">
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 11pt; color: #1a1a1a; padding: 20mm; }
  h1 { font-size: 18pt; color: #6d28d9; margin-bottom: 4mm; }
  h2 { font-size: 12pt; color: #4c1d95; border-bottom: 1px solid #ddd6fe; margin: 6mm 0 3mm; padding-bottom: 1mm; }
  .header { display: flex; justify-content: space-between; margin-bottom: 8mm; }
  .logo { font-size: 20pt; font-weight: bold; color: #6d28d9; }
  .meta { text-align: right; font-size: 9pt; color: #555; }
  table { width: 100%; border-collapse: collapse; margin-top: 2mm; }
  th { background: #f3f0ff; color: #4c1d95; text-align: left; padding: 2mm 3mm; font-size: 10pt; }
  td { padding: 2mm 3mm; border-bottom: 1px solid #f0f0f0; font-size: 10pt; }
  .badge { display: inline-block; padding: 1mm 3mm; border-radius: 3mm; font-size: 9pt; font-weight: bold; }
  .badge-open       { background: #dbeafe; color: #1d4ed8; }
  .badge-in_progress { background: #fef9c3; color: #854d0e; }
  .badge-done       { background: #dcfce7; color: #166534; }
  .badge-problem    { background: #fee2e2; color: #991b1b; }
  .badge-high   { background: #fef3c7; color: #92400e; }
  .badge-urgent { background: #fee2e2; color: #991b1b; }
  .badge-medium { background: #dbeafe; color: #1e40af; }
  .badge-low    { background: #f0fdf4; color: #166534; }
  .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 4mm; margin-top: 3mm; }
  .info-item label { font-size: 9pt; color: #777; display: block; margin-bottom: 1mm; }
  .info-item span  { font-size: 10pt; font-weight: bold; }
  .desc-box { background: #faf5ff; border: 1px solid #e9d5ff; border-radius: 2mm; padding: 3mm; margin-top: 2mm; font-size: 10pt; line-height: 1.5; }
  .footer { margin-top: 10mm; border-top: 1px solid #ddd; padding-top: 3mm; font-size: 8pt; color: #888; text-align: center; }
  .sign-box { border: 1px solid #ccc; height: 25mm; margin-top: 2mm; border-radius: 2mm; }
  .sign-row { display: grid; grid-template-columns: 1fr 1fr; gap: 6mm; margin-top: 6mm; }
</style>
</head>
<body>

<div class="header">
  <div>
    <div class="logo"><?= esc($tenant['company_name'] ?? 'WorkHub') ?></div>
    <div style="font-size:9pt;color:#777;margin-top:1mm;"><?= esc($tenant['address'] ?? '') ?></div>
  </div>
  <div class="meta">
    <strong>WORK ORDER</strong><br>
    No: WO-<?= esc(str_pad($task['id'], 6, '0', STR_PAD_LEFT)) ?><br>
    Date: <?= date('d.m.Y') ?><br>
    <?php if (!empty($task['due_date'])): ?>
    Due: <?= date('d.m.Y', strtotime($task['due_date'])) ?><br>
    <?php endif; ?>
  </div>
</div>

<h1><?= esc($task['title'] ?? 'Work Order') ?></h1>

<h2>Task Details</h2>
<div class="info-grid">
  <div class="info-item"><label>Status</label>
    <span><span class="badge badge-<?= esc($task['status'] ?? 'open') ?>"><?= ucfirst(str_replace('_', ' ', $task['status'] ?? 'open')) ?></span></span>
  </div>
  <div class="info-item"><label>Priority</label>
    <span><span class="badge badge-<?= esc($task['priority'] ?? 'medium') ?>"><?= ucfirst($task['priority'] ?? 'Medium') ?></span></span>
  </div>
  <div class="info-item"><label>Project</label>
    <span><?= esc($task['project_name'] ?? '—') ?></span>
  </div>
  <div class="info-item"><label>Location</label>
    <span><?= esc($task['location_tag'] ?? '—') ?></span>
  </div>
  <div class="info-item"><label>Assigned Worker</label>
    <span><?= esc($worker['name'] ?? '—') ?></span>
  </div>
  <div class="info-item"><label>Estimated Hours</label>
    <span><?= esc($task['est_hours'] ?? '—') ?> h</span>
  </div>
</div>

<?php if (!empty($task['description'])): ?>
<h2>Description / Scope of Work</h2>
<div class="desc-box"><?= nl2br(esc($task['description'])) ?></div>
<?php endif; ?>

<h2>Materials Required</h2>
<?php if (!empty($materials)): ?>
<table>
  <tr><th>Material</th><th>Quantity</th><th>Unit</th><th>Catalogue Ref</th></tr>
  <?php foreach ($materials as $m): ?>
  <tr>
    <td><?= esc($m['material_name']) ?></td>
    <td><?= esc($m['quantity']) ?></td>
    <td><?= esc($m['unit']) ?></td>
    <td><?= esc($m['catalogue_ref'] ?? '—') ?></td>
  </tr>
  <?php endforeach; ?>
</table>
<?php else: ?>
<p style="color:#777;font-size:10pt;margin-top:2mm;">No materials specified.</p>
<?php endif; ?>

<div class="sign-row">
  <div>
    <h2>Planner / Manager Sign-off</h2>
    <div class="sign-box"></div>
    <p style="font-size:9pt;color:#777;margin-top:1mm;">Name &amp; Date</p>
  </div>
  <div>
    <h2>Worker Acknowledgement</h2>
    <div class="sign-box"></div>
    <p style="font-size:9pt;color:#777;margin-top:1mm;">Name &amp; Date</p>
  </div>
</div>

<div class="footer">
  Generated by <?= esc($tenant['company_name'] ?? 'WorkHub') ?> · <?= date('d.m.Y H:i') ?> ·
  This document is for internal use only.
</div>
</body>
</html>
