<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

/**
 * Deterministic WorkHub seed for E2E/API tests.
 *
 * Guarantees that the nexus.ai tenant always has:
 *   - workhub_workers row ID 1 → alex.rivera (manager)
 *   - workhub_workers row ID 2 → mark.davis  (worker)
 *   - A sample project for task-related tests
 *   - Tasks in each status: open, in_progress, done, problem
 *
 * Run after MainSeeder:
 *   php spark db:seed WorkHubTestSeeder
 *
 * Safe to re-run: clears and repopulates workhub tables for the nexus.ai tenant only.
 */
class WorkHubTestSeeder extends Seeder
{
    public function run()
    {
        $db = \Config\Database::connect();

        // ── Locate nexus.ai tenant ────────────────────────────────────────────
        $tenant = $db->table('tenants')->where('subdomain', 'nexus_ai')->get()->getRow();
        if (!$tenant) {
            echo "WorkHubTestSeeder: nexus_ai tenant not found — run MainSeeder first.\n";
            return;
        }
        $tid = $tenant->id;

        // ── Locate users ──────────────────────────────────────────────────────
        $manager = $db->table('users')->where('email', 'alex.rivera@nexus.ai')->get()->getRow();

        if (!$manager) {
            echo "WorkHubTestSeeder: alex.rivera@nexus.ai not found — run MainSeeder first.\n";
            return;
        }

        // Ensure mark.davis@nexus.ai exists (not generated by MainSeeder's random names)
        $worker = $db->table('users')->where('email', 'mark.davis@nexus.ai')->get()->getRow();
        if (!$worker) {
            $db->table('users')->insert([
                'tenant_id'     => $tid,
                'email'         => 'mark.davis@nexus.ai',
                'password_hash' => password_hash('password123', PASSWORD_BCRYPT),
                'name'          => 'Mark Davis',
                'role'          => 'user',
                'created_at'    => date('Y-m-d H:i:s'),
            ]);
            $worker = $db->table('users')->where('email', 'mark.davis@nexus.ai')->get()->getRow();
            echo "WorkHubTestSeeder: created mark.davis@nexus.ai worker user.\n";
        }

        // ── Reset WorkHub tables for this tenant (keep other tenants intact) ──
        $db->query('SET FOREIGN_KEY_CHECKS=0');
        $db->table('workhub_tasks')->where('tenant_id', $tid)->delete();
        $db->table('workhub_workers')->where('tenant_id', $tid)->delete();
        // Reset auto-increment so IDs are predictable (1, 2)
        $maxWorker = $db->table('workhub_workers')->selectMax('id')->get()->getRow();
        if (!$maxWorker->id) {
            $db->query('ALTER TABLE workhub_workers AUTO_INCREMENT = 1');
        }
        $db->query('SET FOREIGN_KEY_CHECKS=1');

        // ── Seed workers (ID 1 = manager, ID 2 = worker) ─────────────────────
        $db->table('workhub_workers')->insert([
            'tenant_id'               => $tid,
            'user_id'                 => $manager->id,
            'wh_role'                 => 'manager',
            'capacity_hours_per_week' => 40.00,
            'hourly_rate'             => 85.00,
            'language_pref'           => 'en',
            'active'                  => 1,
            'created_at'              => date('Y-m-d H:i:s'),
        ]);
        $managerId = $db->insertID(); // expected: 1

        $db->table('workhub_workers')->insert([
            'tenant_id'               => $tid,
            'user_id'                 => $worker->id,
            'wh_role'                 => 'worker',
            'capacity_hours_per_week' => 40.00,
            'hourly_rate'             => 55.00,
            'language_pref'           => 'en',
            'active'                  => 1,
            'created_at'              => date('Y-m-d H:i:s'),
        ]);
        $workerId = $db->insertID(); // expected: 2

        echo "WorkHub workers seeded: manager={$managerId}, worker={$workerId}\n";

        // ── Seed a project ────────────────────────────────────────────────────
        $existingProject = $db->table('workhub_projects')->where('tenant_id', $tid)->get()->getRow();
        $projectId = null;
        if (!$existingProject) {
            $db->table('workhub_projects')->insert([
                'tenant_id'  => $tid,
                'name'       => 'Test Project Alpha',
                'status'     => 'active',
                'created_at' => date('Y-m-d H:i:s'),
            ]);
            $projectId = $db->insertID();
        } else {
            $projectId = $existingProject->id;
        }

        // ── Seed tasks (one in each status) ──────────────────────────────────
        $now  = date('Y-m-d H:i:s');
        $soon = date('Y-m-d', strtotime('+7 days'));

        $tasks = [
            [
                'tenant_id'          => $tid,
                'project_id'         => $projectId,
                'assigned_worker_id' => $workerId,
                'created_by'         => $manager->id,
                'title'              => 'E2E Open Task — install electrical panel',
                'description'        => 'Replace main electrical panel in unit 3B.',
                'status'             => 'open',
                'priority'           => 'high',
                'est_hours'          => 4.00,
                'logged_hours'       => 0.00,
                'due_date'           => $soon,
                'created_at'         => $now,
            ],
            [
                'tenant_id'          => $tid,
                'project_id'         => $projectId,
                'assigned_worker_id' => $workerId,
                'created_by'         => $manager->id,
                'title'              => 'E2E In-Progress Task — HVAC maintenance',
                'description'        => 'Service HVAC system on floors 2–4.',
                'status'             => 'in_progress',
                'priority'           => 'medium',
                'est_hours'          => 6.00,
                'logged_hours'       => 2.50,
                'due_date'           => $soon,
                'created_at'         => $now,
            ],
            [
                'tenant_id'          => $tid,
                'project_id'         => $projectId,
                'assigned_worker_id' => $workerId,
                'created_by'         => $manager->id,
                'title'              => 'E2E Done Task — fire alarm inspection',
                'description'        => 'Annual fire alarm compliance inspection.',
                'status'             => 'done',
                'priority'           => 'low',
                'est_hours'          => 2.00,
                'logged_hours'       => 2.00,
                'due_date'           => date('Y-m-d', strtotime('-2 days')),
                'created_at'         => $now,
            ],
            [
                'tenant_id'          => $tid,
                'project_id'         => null,
                'assigned_worker_id' => $workerId,
                'created_by'         => $manager->id,
                'title'              => 'E2E Problem Task — water leak investigation',
                'description'        => 'Leak detected in basement utility room.',
                'status'             => 'problem',
                'priority'           => 'urgent',
                'est_hours'          => 3.00,
                'logged_hours'       => 0.00,
                'due_date'           => $soon,
                'created_at'         => $now,
            ],
            [
                'tenant_id'          => $tid,
                'project_id'         => $projectId,
                'assigned_worker_id' => $managerId,
                'created_by'         => $manager->id,
                'title'              => 'E2E Manager Task — site survey',
                'description'        => 'Conduct quarterly site safety survey.',
                'status'             => 'open',
                'priority'           => 'medium',
                'est_hours'          => 3.00,
                'logged_hours'       => 0.00,
                'due_date'           => $soon,
                'created_at'         => $now,
            ],
        ];

        $db->table('workhub_tasks')->insertBatch($tasks);
        echo 'WorkHub tasks seeded: ' . count($tasks) . " tasks.\n";

        // ── Assign Worker rights to mark.davis ───────────────────────────────────
        // Clear any existing roles/user_roles for nexus_ai tenant users
        $db->table('user_roles')
            ->whereIn('user_id', [$worker->id, $manager->id])
            ->delete();
        $existingRoles = $db->table('roles')->select('id')->where('tenant_id', $tid)->get()->getResultArray();
        $existingRoleIds = array_column($existingRoles, 'id');
        if (!empty($existingRoleIds)) {
            $db->table('role_rights')->whereIn('role_id', $existingRoleIds)->delete();
        }
        $db->table('roles')->where('tenant_id', $tid)->delete();

        // Create Worker role (task.view + timer.start only — no completion.submit so WTS-07 stays 403)
        $db->table('roles')->insert([
            'tenant_id'      => $tid,
            'name'           => 'Worker',
            'description'    => 'Field worker — task view and timer rights',
            'is_super_admin' => 0,
        ]);
        $workerRoleId = $db->insertID();

        // Look up right IDs by code — safer than hardcoding after each migration
        $taskViewRight   = $db->table('rights')->where('code', 'workhub.task.view')->get()->getRow();
        $timerStartRight = $db->table('rights')->where('code', 'workhub.timer.start')->get()->getRow();

        if ($taskViewRight) {
            $db->table('role_rights')->insert(['role_id' => $workerRoleId, 'right_id' => $taskViewRight->id]);
        }
        if ($timerStartRight) {
            $db->table('role_rights')->insert(['role_id' => $workerRoleId, 'right_id' => $timerStartRight->id]);
        }

        // Assign mark.davis to Worker role
        $db->table('user_roles')->insert(['user_id' => $worker->id, 'role_id' => $workerRoleId]);
        echo "WorkHubTestSeeder: assigned Worker role to mark.davis (task.view + timer.start, no completion.submit).\n";

        echo "WorkHubTestSeeder complete.\n";
    }
}
